// scripts/seed-peptide-reference.ts
// Reads CATALOG_PRESETS.peptides and writes an idempotent seed migration
// for the peptide_reference table. Re-run after editing CURATED_ALIASES or
// after CATALOG_PRESETS changes.
//
// Usage:  npx tsx scripts/seed-peptide-reference.ts
import { CATALOG_PRESETS } from '../src/lib/catalog-presets'
import * as fs from 'node:fs'
import * as path from 'node:path'

/** Hand-curated synonyms / nicknames / brand names per compound. Auto-generated
 * aliases (de-hyphenated, spaced) come on top of these. */
const CURATED_ALIASES: Record<string, string[]> = {
  'Semaglutide 10mg':            ['SEMA', 'Sema', 'semaglutide', 'Ozempic', 'Wegovy', 'GLP-1'],
  'Tirzepatide 30mg':            ['TIRZ', 'Tirz', 'tirzepatide', 'Mounjaro', 'Zepbound'],
  'Retatrutide 10mg':            ['RETA', 'Reta', 'retatrutide', 'Triple G'],
  'BPC-157 5mg':                 ['BPC157', 'BPC 157', 'Body Protection Compound', 'Body Protective Compound'],
  'TB-500 5mg':                  ['TB500', 'TB 500', 'Thymosin Beta-4', 'Thymosin Beta 4'],
  'Thymosin Alpha-1 5mg':        ['TA1', 'TA-1', 'Zadaxin', 'Thymosin Alpha 1'],
  'BPC-157+TB-500 Blend 5mg+5mg':['BPC TB Blend', 'Wolverine', 'BPC/TB Blend'],
  'KPV 5mg':                     ['KPV', 'Lysine-Proline-Valine'],
  'LL-37 5mg':                   ['LL37', 'LL 37', 'Cathelicidin'],
  'Tesamorelin 10mg':            ['TESA', 'Tesa', 'tesamorelin', 'Egrifta'],
  'CJC-1295 5mg':                ['CJC1295', 'CJC 1295', 'CJC'],
  'Ipamorelin 5mg':              ['IPAM', 'Ipam', 'ipamorelin'],
  'CJC-1295+Ipamorelin Blend 5mg+5mg': ['CJC Ipa Blend', 'CJC/Ipa'],
  'Hexarelin 5mg':               ['Hex', 'hexarelin'],
  'IGF-1 LR3 1mg':               ['IGF1 LR3', 'IGF1LR3', 'IGF-1 long R3', 'Long R3 IGF-1'],
  '5-Amino-1MQ 50mg':            ['5Amino1MQ', '5 Amino 1MQ', 'Aminoquinoline'],
  'MOTS-c 10mg':                 ['MOTSc', 'MOTS c', 'MOTS-C'],
  'SS-31 5mg':                   ['SS31', 'SS 31', 'Elamipretide'],
  'NAD+ 500mg':                  ['NAD', 'NAD plus', 'Nicotinamide Adenine Dinucleotide'],
  'Semax 10mg':                  ['SEMAX', 'semax', 'Heptapeptide ACTH'],
  'Selank 10mg':                 ['SELANK', 'selank'],
  'DSIP 2mg':                    ['Delta Sleep-Inducing Peptide', 'Delta Sleep Inducing Peptide'],
  'Cerebrolysin 60mg':           ['Cere', 'cerebrolysin'],
  'GHK-Cu 50mg':                 ['GHKCu', 'GHK Cu', 'Copper Tripeptide', 'Copper Peptide'],
  'Melanotan II 10mg':           ['MT2', 'MT-2', 'Melanotan 2', 'Melanotan-II'],
  'PT-141 10mg':                 ['PT141', 'PT 141', 'Bremelanotide', 'Vyleesi'],
  'Kisspeptin-10 10mg':          ['KP10', 'Kisspeptin 10', 'Kisspeptin', 'KP-10'],
  'Epithalon 10mg':              ['Epitalon', 'Epi', 'epithalon', 'epitalon'],
}

function autoAliases(name: string): string[] {
  const stripDose = (s: string) => s.replace(/\s+\d+(?:\.\d+)?\s*(?:mg|mcg|iu|ml|caps?)\b.*$/i, '').trim()
  const set = new Set<string>()
  set.add(name)
  const noDose = stripDose(name)
  if (noDose && noDose !== name) set.add(noDose)
  // Hyphen variants on the no-dose form
  if (noDose.includes('-')) {
    set.add(noDose.replace(/-/g, ''))   // BPC-157 → BPC157
    set.add(noDose.replace(/-/g, ' '))  // BPC-157 → BPC 157
  }
  return [...set]
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function sqlNumber(value: number | null | undefined): string {
  return value === null || value === undefined ? 'NULL' : String(value)
}

function sqlJsonb(value: string[]): string {
  const escaped = JSON.stringify(value).replace(/'/g, "''")
  return `'${escaped}'::jsonb`
}

const peptides = CATALOG_PRESETS.peptides
const statements: string[] = [
  '-- Generated by scripts/seed-peptide-reference.ts. Do not edit by hand —',
  '-- update CURATED_ALIASES or CATALOG_PRESETS and re-run the script.',
  '',
]

for (const p of peptides) {
  const aliases = [...new Set([
    ...autoAliases(p.name),
    ...(CURATED_ALIASES[p.name] ?? []),
  ])].filter(a => a && a !== p.name)
  const proto = p.protocol ?? null
  statements.push(`INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  ${sqlString(p.name)},
  ${sqlString(p.product_family)},
  ${sqlString(p.description ?? '')},
  ${sqlJsonb(aliases)},
  ${proto?.vial_strength ? sqlString(proto.vial_strength) : 'NULL'},
  ${sqlNumber(proto?.reconstitution_ml ?? null)},
  ${sqlNumber(proto?.draw_volume_ml ?? null)},
  ${proto?.frequency ? sqlString(proto.frequency) : 'NULL'},
  ${proto?.timing ? sqlString(proto.timing) : 'NULL'},
  ${sqlNumber(proto?.cycle_length_weeks ?? null)},
  ${proto?.notes ? sqlString(proto.notes) : 'NULL'},
  ${proto?.dose_display ? sqlString(proto.dose_display) : 'NULL'}
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();`)
}

const outPath = path.join('supabase', 'migrations', '20260525000002_peptide_reference_seed.sql')
fs.writeFileSync(outPath, statements.join('\n\n') + '\n')
console.log(`Wrote ${peptides.length} peptide reference rows to ${outPath}`)
