-- Generated by scripts/seed-peptide-reference.ts. Do not edit by hand —

-- update CURATED_ALIASES or CATALOG_PRESETS and re-run the script.



INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Semaglutide 10mg',
  'GLP-1',
  'GLP-1 receptor agonist that suppresses appetite and slows gastric emptying; widely researched for metabolic health and weight management.',
  '["Semaglutide","SEMA","Sema","semaglutide","Ozempic","Wegovy","GLP-1"]'::jsonb,
  '10mg/vial',
  2,
  0.05,
  'weekly',
  'morning',
  12,
  NULL,
  '0.25mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Tirzepatide 30mg',
  'GLP-1',
  'Dual GIP/GLP-1 receptor agonist with superior weight-loss outcomes in trials; reduces appetite and improves insulin sensitivity.',
  '["Tirzepatide","TIRZ","Tirz","tirzepatide","Mounjaro","Zepbound"]'::jsonb,
  '30mg/vial',
  2,
  0.017,
  'weekly',
  'morning',
  12,
  NULL,
  '2.5mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Retatrutide 10mg',
  'GLP-1',
  'Triple GIP/GLP-1/glucagon receptor agonist showing exceptional fat-loss results in Phase 2 trials; next-generation metabolic peptide.',
  '["Retatrutide","RETA","Reta","retatrutide","Triple G"]'::jsonb,
  '10mg/vial',
  2,
  0.1,
  'weekly',
  'morning',
  12,
  NULL,
  '0.5mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'BPC-157 5mg',
  'HEALING',
  'Body Protection Compound-157; accelerates soft tissue, tendon, and gut healing via angiogenesis and growth factor upregulation.',
  '["BPC-157","BPC157","BPC 157","Body Protection Compound","Body Protective Compound"]'::jsonb,
  '5mg/vial',
  2,
  0.1,
  'once_daily',
  'morning',
  10,
  NULL,
  '250mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'TB-500 5mg',
  'HEALING',
  'Synthetic analog of Thymosin Beta-4; promotes tissue repair, reduces inflammation, and supports muscle and connective tissue recovery.',
  '["TB-500","TB500","TB 500","Thymosin Beta-4","Thymosin Beta 4"]'::jsonb,
  '5mg/vial',
  2,
  0.8,
  '3x_weekly',
  'morning',
  8,
  'Loading phase 4–6 weeks; reduce to weekly for maintenance.',
  '2mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Thymosin Alpha-1 5mg',
  'HEALING',
  '28-amino-acid thymic peptide that modulates T-cell maturation and innate immune response; researched for immune dysfunction and oncology support.',
  '["Thymosin Alpha-1","Thymosin Alpha1","Thymosin Alpha 1","TA1","TA-1","Zadaxin"]'::jsonb,
  '5mg/vial',
  2,
  0.64,
  '3x_weekly',
  'morning',
  6,
  NULL,
  '1.6mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'LL-37 5mg',
  'HEALING',
  'Human cathelicidin-derived antimicrobial peptide with broad-spectrum antibacterial, antiviral, and immunomodulatory activity; promotes wound healing.',
  '["LL-37","LL37","LL 37","Cathelicidin"]'::jsonb,
  '5mg/vial',
  2,
  0.04,
  'once_daily',
  'morning',
  6,
  NULL,
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'CJC-1295 No DAC 5mg',
  'GH',
  'Modified GHRH analog (Mod GRF 1-29) without DAC; short-duration GH pulse, typically paired with a GHRP for synergistic GH secretion.',
  '["CJC-1295 No DAC","CJC1295 No DAC","CJC 1295 No DAC"]'::jsonb,
  '5mg/vial',
  2,
  0.04,
  'once_daily',
  'nightly',
  12,
  'Stack with Ipamorelin or GHRP-2 for synergistic effect.',
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'CJC-1295 w/ DAC 2mg',
  'GH',
  'Long-acting GHRH analog with Drug Affinity Complex extending half-life to ~8 days; provides sustained GH elevation with once-weekly dosing.',
  '["CJC-1295 w/ DAC","CJC1295 w/ DAC","CJC 1295 w/ DAC"]'::jsonb,
  '2mg/vial',
  2,
  1,
  'weekly',
  'nightly',
  12,
  NULL,
  '1mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Ipamorelin 5mg',
  'GH',
  'Selective GHRP that stimulates pulsatile GH release with minimal effect on cortisol or prolactin; used for body composition and recovery.',
  '["Ipamorelin","IPAM","Ipam","ipamorelin"]'::jsonb,
  '5mg/vial',
  2,
  0.04,
  'once_daily',
  'nightly',
  12,
  NULL,
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Sermorelin 5mg',
  'GH',
  'Synthetic analog of endogenous GHRH (first 29 amino acids); stimulates pituitary to release natural GH pulses; used for anti-aging and hormone optimization.',
  '["Sermorelin"]'::jsonb,
  '5mg/vial',
  2,
  0.08,
  '5_on_2_off',
  'nightly',
  12,
  NULL,
  '200mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'GHRP-2 5mg',
  'GH',
  'Second-generation growth hormone releasing peptide; stimulates strong GH pulses with moderate increases in cortisol and prolactin.',
  '["GHRP-2","GHRP2","GHRP 2"]'::jsonb,
  '5mg/vial',
  2,
  0.04,
  'once_daily',
  'nightly',
  12,
  NULL,
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'GHRP-6 5mg',
  'GH',
  'First-generation hexapeptide GHRP; stimulates GH release and significantly increases appetite via ghrelin receptor activation; popular for bulking.',
  '["GHRP-6","GHRP6","GHRP 6"]'::jsonb,
  '5mg/vial',
  2,
  0.04,
  'once_daily',
  'nightly',
  12,
  NULL,
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'AOD-9604 5mg',
  'GH',
  'C-terminal fragment of human growth hormone (hGH 176–191) that mimics GH''s lipolytic effects without affecting IGF-1 or blood glucose.',
  '["AOD-9604","AOD9604","AOD 9604"]'::jsonb,
  '5mg/vial',
  2,
  0.12,
  'once_daily',
  'morning fasted',
  10,
  NULL,
  '300mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'GHK-Cu 50mg',
  'COSMETIC',
  'Naturally occurring copper-binding tripeptide with potent anti-aging, wound healing, and anti-inflammatory properties; stimulates collagen synthesis.',
  '["GHK-Cu","GHKCu","GHK Cu","Copper Tripeptide","Copper Peptide"]'::jsonb,
  '50mg/vial',
  2,
  0.04,
  '3x_weekly',
  'evening',
  8,
  NULL,
  '1mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Epithalon 10mg',
  'COSMETIC',
  'Synthetic tetrapeptide that activates telomerase to lengthen telomeres; researched for longevity, sleep improvement, and circadian rhythm restoration.',
  '["Epithalon","Epitalon","Epi","epithalon","epitalon"]'::jsonb,
  '10mg/vial',
  2,
  1,
  'once_daily',
  'evening',
  2,
  'Run as a 10–20 day intensive cycle; repeat 2–3x per year.',
  '5mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'PT-141 10mg',
  'COSMETIC',
  'Melanocortin receptor agonist (MC3R/MC4R) researched for sexual dysfunction in both males and females; acts centrally on hypothalamic pathways.',
  '["PT-141","PT141","PT 141","Bremelanotide","Vyleesi"]'::jsonb,
  '10mg/vial',
  2,
  0.2,
  '3x_weekly',
  '45–60 min before activity',
  4,
  'On-demand use only; allow 48h between doses.',
  '1mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Melanotan II 10mg',
  'COSMETIC',
  'Cyclic melanocortin analog that stimulates melanogenesis (tanning) and has pro-erectile effects; requires UV exposure for full pigmentation.',
  '["Melanotan II","MT2","MT-2","Melanotan 2","Melanotan-II"]'::jsonb,
  '10mg/vial',
  2,
  0.05,
  'once_daily',
  'evening',
  6,
  'Loading 3 weeks daily, then maintenance 2–3x weekly.',
  '250mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Selank 10mg',
  'NEURO',
  'Synthetic heptapeptide anxiolytic derived from tuftsin; modulates GABAergic and serotonergic systems to reduce anxiety and improve cognitive performance.',
  '["Selank","SELANK","selank"]'::jsonb,
  '10mg/vial',
  2,
  0.06,
  'once_daily',
  'morning',
  4,
  NULL,
  '300mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Semax 10mg',
  'NEURO',
  'Synthetic ACTH(4-7)PGP analog that upregulates BDNF and NGF; studied for cognitive enhancement, neuroprotection, and CNS injury recovery.',
  '["Semax","SEMAX","semax","Heptapeptide ACTH"]'::jsonb,
  '10mg/vial',
  2,
  0.1,
  '5_on_2_off',
  'morning',
  8,
  NULL,
  '500mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Dihexa 5mg',
  'NEURO',
  'Hepatocyte growth factor (HGF) potentiator derived from angiotensin IV; promotes synaptogenesis and neurotrophic signaling; studied for cognitive decline.',
  '["Dihexa"]'::jsonb,
  '5mg/vial',
  2,
  0.8,
  '5_on_2_off',
  'morning',
  8,
  NULL,
  '2mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'DSIP 5mg',
  'NEURO',
  'Delta Sleep-Inducing Peptide; endogenous nonapeptide that promotes slow-wave sleep, modulates stress responses, and normalizes cortisol rhythms.',
  '["DSIP"]'::jsonb,
  '5mg/vial',
  2,
  0.04,
  '5_on_2_off',
  'evening',
  4,
  NULL,
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'SS-31 10mg',
  'MITO',
  'Mitochondria-targeted tetrapeptide (Elamipretide) that binds cardiolipin on the inner mitochondrial membrane, improving electron transport chain efficiency.',
  '["SS-31","SS31","SS 31"]'::jsonb,
  '10mg/vial',
  2,
  1,
  'once_daily',
  'morning',
  10,
  NULL,
  '5mg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Humanin 10mg',
  'MITO',
  'Mitochondrial-derived peptide (MDP) that exerts cytoprotective and anti-apoptotic effects; researched for neuroprotection, metabolic health, and longevity.',
  '["Humanin"]'::jsonb,
  '10mg/vial',
  2,
  0.1,
  'weekly',
  'morning',
  6,
  NULL,
  '500mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Kisspeptin-10 10mg',
  'MITO',
  'Decapeptide that stimulates pulsatile GnRH release, triggering LH and FSH secretion; researched for HPG axis restoration and fertility support.',
  '["Kisspeptin-10","Kisspeptin10","Kisspeptin 10","KP10","Kisspeptin","KP-10"]'::jsonb,
  '10mg/vial',
  2,
  0.02,
  'eod',
  'morning',
  4,
  'Avoid continuous daily use to prevent receptor desensitization.',
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();

INSERT INTO peptide_reference (
  canonical_name, family, description, aliases,
  vial_strength, reconstitution_ml, draw_volume_ml,
  frequency, timing, cycle_length_weeks, notes, dose_display
) VALUES (
  'Gonadorelin 2mg',
  'MITO',
  'Synthetic GnRH that stimulates pituitary LH and FSH release; used in TRT-adjunct protocols to maintain testicular function and fertility.',
  '["Gonadorelin"]'::jsonb,
  '2mg/vial',
  2,
  0.1,
  '3x_weekly',
  'morning',
  12,
  NULL,
  '100mcg'
)
ON CONFLICT (canonical_name) DO UPDATE SET
  family             = EXCLUDED.family,
  description        = EXCLUDED.description,
  aliases            = EXCLUDED.aliases,
  vial_strength      = EXCLUDED.vial_strength,
  reconstitution_ml  = EXCLUDED.reconstitution_ml,
  draw_volume_ml     = EXCLUDED.draw_volume_ml,
  frequency          = EXCLUDED.frequency,
  timing             = EXCLUDED.timing,
  cycle_length_weeks = EXCLUDED.cycle_length_weeks,
  notes              = EXCLUDED.notes,
  dose_display       = EXCLUDED.dose_display,
  updated_at         = now();
